import { IMenu } from '../interface/i-menu';

export const starterList: Array<IMenu> = [
  {
    id: 1,
    name: 'Achari Paneer Tikka',
    image: '/assets/Achari Paneer Tikka.png',
    selected: false,
    quantity: 2,
    unit: 'pcs',
    price: 400,
  },
  {
    id: 2,
    name: 'Butter Steamed Corn',
    image: '/assets/Butter Steamed Corn.png',
    selected: false,
    quantity: 1,
    unit: 'kgs',
  },
  {
    id: 3,
    name: 'Cajun Spice Potato',
    image: '/assets/Cajun Spice Potato.png',
    selected: false,
    quantity: 1,
    unit: 'kgs',
  },
  {
    id: 4,
    name: 'Veg Spring Rolls',
    image: '/assets/Veg Spring Rolls.png',
    selected: false,
    quantity: 1,
    unit: 'pcs',
  },
  {
    id: 5,
    name: 'Hara Bhara Kabab',
    image: '/assets/Hara Bhara Kabab.png',
    selected: false,
    quantity: 1,
    unit: 'pcs',
  },
  {
    id: 6,
    name: 'Crispy Veg',
    image: '/assets/Crispy Veg.png',
    selected: false,
    quantity: 1,
    unit: 'kgs',
  },
  {
    id: 7,
    name: 'Paneer Malai Tikka',
    image: '/assets/Paneer Malai Tikka.png',
    selected: false,
    quantity: 1,
    unit: 'pcs',
  },
  {
    id: 8,
    name: 'Veg Manchurian',
    image: '/assets/Veg Manchurian.png',
    selected: false,
    quantity: 1,
    unit: 'pcs',
  },
  {
    id: 9,
    name: 'Chilli Mushroom',
    image: '/assets/Chilli Mushroom.png',
    selected: false,
    quantity: 1,
    unit: 'kgs',
  },
  {
    id: 10,
    name: 'Stuffed Tandoori Aloo',
    image: '/assets/Stuffed Tandoori Aloo.png',
    selected: false,
    quantity: 1,
    unit: 'pcs',
  },
  {
    id: 11,
    name: 'Corn Cheese Balls',
    image: '/assets/Corn Cheese Balls.png',
    selected: false,
    unit: 'pcs',
  },
  {
    id: 12,
    name: 'Tandoori Broccoli',
    image: '/assets/Tandoori Broccoli.png',
    selected: false,
    quantity: 1,
    unit: 'kgs',
  },
];
